services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn record_proj.wsgi:application
    runtime: python3.12.4  # Ensure this matches your `runtime.txt`
